name: Build Clash-Verge-Rev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        profile: minimal
        override: true

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm i

    - name: Run build
      run: pnpm build

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: clash-verge-rev-build
        path: ./src-tauri/target/release/
